#define yy_create_buffer cpp__create_buffer
#define yy_delete_buffer cpp__delete_buffer
#define yy_scan_buffer cpp__scan_buffer
#define yy_scan_string cpp__scan_string
#define yy_scan_bytes cpp__scan_bytes
#define yy_flex_debug cpp__flex_debug
#define yy_init_buffer cpp__init_buffer
#define yy_flush_buffer cpp__flush_buffer
#define yy_load_buffer_state cpp__load_buffer_state
#define yy_switch_to_buffer cpp__switch_to_buffer
#define yyin cpp_in
#define yyleng cpp_leng
#define yylex cpp_lex
#define yyout cpp_out
#define yyrestart cpp_restart
#define yytext cpp_text
#define yylineno cpp_lineno
#define yywrap cpp_wrap

/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 82
#define YY_END_OF_BUFFER 83
static yyconst short int yy_acclist[359] =
    {   0,
       83,   82,    4,   82,   17,   82,   82,   32,   82,   34,
       82,   25,   82,   26,   82,   12,   82,   29,   82,   19,
       82,   16,   30,   82,   33,   82,   31,   82,    1,   82,
       28,   82,   22,   82,   15,   82,   13,   82,   14,   82,
       27,   82,   82,   23,   82,   24,   82,   36,   82,   80,
       82,   80,   82,   80,   82,   80,   82,   80,   82,   80,
       82,   80,   82,   80,   82,   80,   82,   80,   82,   80,
       82,   80,   82,   80,   82,   80,   82,   80,   82,   80,
       82,   80,   82,   80,   82,   20,   82,   35,   82,   21,
       82,   18,   82,   11,    3,    7,    8,    9,    1,    6,

       10,   81,   80,   80,   80,   80,   80,   80,   56,   80,
       80,   80,   80,   80,   80,   80,   80,   52,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,    5,    2,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   55,   80,   80,   80,   41,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   70,   80,   39,   80,   37,   80,   80,   80,
       80,   80,   53,   80,   80,   80,   80,   80,   80,   80,

       42,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   66,   80,   78,   80,   80,
       80,   80,   80,   47,   80,   80,   80,   80,   60,   80,
       63,   80,   80,   80,   80,   80,   79,   80,   45,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   40,
       80,   80,   80,   80,   80,   80,   80,   62,   80,   80,
       80,   80,   80,   57,   80,   80,   46,   80,   80,   80,
       65,   80,   77,   80,   74,   80,   80,   80,   80,   80,
       69,   80,   80,   80,   43,   80,   58,   80,   72,   80,
       61,   80,   54,   80,   80,   80,   80,   80,   80,   80,

       80,   80,   73,   80,   80,   67,   80,   80,   80,   80,
       80,   59,   80,   80,   75,   80,   80,   38,   80,   80,
       80,   76,   80,   80,   80,   71,   80,   80,   80,   44,
       80,   63,   80,   80,   80,   64,   80,   68,   80,   80,
       80,   51,   80,   80,   80,   80,   80,   80,   48,   80,
       50,   80,   80,   80,   80,   80,   49,   80
    } ;

static yyconst short int yy_accept[278] =
    {   0,
        1,    1,    1,    2,    3,    5,    7,    8,   10,   12,
       14,   16,   18,   20,   22,   25,   27,   29,   31,   33,
       35,   37,   39,   41,   43,   44,   46,   48,   50,   52,
       54,   56,   58,   60,   62,   64,   66,   68,   70,   72,
       74,   76,   78,   80,   82,   84,   86,   88,   90,   92,
       94,   95,   95,   96,   97,   98,   99,   99,  100,  101,
      102,  102,  103,  104,  105,  106,  107,  108,  109,  111,
      112,  113,  114,  115,  116,  117,  118,  120,  121,  122,
      123,  124,  125,  126,  127,  128,  129,  130,  131,  132,
      133,  134,  135,  136,  137,  138,  139,  140,  140,  141,

      142,  143,  144,  145,  146,  147,  148,  149,  150,  151,
      152,  153,  155,  156,  157,  159,  160,  161,  162,  163,
      164,  165,  166,  167,  168,  169,  170,  171,  172,  173,
      174,  175,  176,  177,  178,  179,  180,  181,  182,  183,
      185,  187,  189,  190,  191,  192,  193,  195,  196,  197,
      198,  199,  200,  201,  203,  204,  205,  206,  207,  208,
      209,  210,  211,  212,  213,  214,  215,  216,  218,  220,
      221,  222,  223,  224,  226,  227,  228,  229,  231,  233,
      234,  235,  236,  237,  239,  241,  242,  243,  244,  245,
      246,  247,  248,  249,  250,  252,  253,  254,  255,  256,

      257,  258,  260,  261,  262,  263,  264,  266,  267,  269,
      270,  271,  273,  275,  277,  278,  279,  280,  281,  283,
      284,  285,  287,  289,  291,  293,  295,  296,  297,  298,
      299,  300,  301,  302,  303,  305,  306,  308,  309,  310,
      311,  312,  314,  315,  317,  318,  320,  321,  322,  324,
      325,  326,  328,  329,  330,  332,  334,  335,  336,  338,
      340,  341,  342,  344,  345,  346,  347,  348,  349,  351,
      353,  354,  355,  356,  357,  359,  359
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    1,    1,    5,    6,    1,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   16,   17,   18,
       19,   20,   21,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   22,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       23,    1,   24,   25,   26,    1,   27,   28,   29,   30,

       31,   32,   33,   34,   35,   36,   36,   37,   38,   39,
       40,   41,   36,   42,   43,   44,   45,   46,   47,   48,
       49,   50,   51,   52,   53,   54,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[55] =
    {   0,
        1,    2,    1,    1,    1,    1,    3,    1,    1,    1,
        1,    1,    1,    1,    3,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        1,    1,    1,    1
    } ;

static yyconst short int yy_base[280] =
    {   0,
        0,    0,  514,  515,  515,  494,  508,  515,  515,  515,
      515,  515,  501,  515,   43,  497,  515,  494,  492,  515,
      515,  488,  515,  515,  502,  515,  515,  515,  498,   49,
       50,   51,   52,   58,   60,   54,   59,   53,   55,   62,
       65,   74,   71,   64,   76,  103,  515,  515,  515,  515,
      515,  500,  499,  515,  515,  515,  489,  486,  515,  515,
      496,  515,  492,   68,   77,  107,  108,  112,   82,  115,
      116,  117,  118,  122,  121,  129,  491,  123,  126,  124,
      119,  131,  141,  137,  133,  142,  149,  139,  143,  132,
      138,  145,  140,  146,  177,  178,  515,  493,  492,  179,

      180,  182,  183,  186,  187,  189,  190,  188,  191,  192,
      193,  488,  196,  195,  487,  198,  201,  202,  194,  197,
      199,  203,  200,  205,  207,  211,  216,  225,  227,  230,
      236,  237,  238,  241,  242,  244,  245,  248,  243,  486,
      484,  481,  246,  247,  250,  252,  478,  249,  251,  254,
      255,  256,  257,  476,  270,  258,  275,  272,  259,  262,
      274,  276,  281,  285,  293,  290,  297,  475,  474,  299,
      300,  301,  302,  473,  304,  303,  306,  472,  307,  309,
      308,  315,  310,  471,  470,  316,  320,  317,  314,  323,
      324,  328,  325,  329,  469,  331,  334,  335,  343,  345,

      349,  468,  351,  355,  356,  352,  467,  363,  466,  364,
      361,  464,  462,  458,  358,  367,  366,  365,  454,  368,
      369,  453,  451,  374,  450,  449,  370,  376,  377,  378,
      379,  381,  391,  388,  448,  396,  446,  397,  394,  398,
      405,  445,  399,  444,  406,  136,  403,  409,  135,  411,
      413,  134,  412,  414,   73,   72,  415,  417,   70,   69,
      419,  420,   67,  423,  424,  426,  428,  438,   66,   63,
      433,  440,  441,  442,   61,  515,  486,   61,  489
    } ;

static yyconst short int yy_def[280] =
    {   0,
      276,    1,  276,  276,  276,  276,  277,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  276,  276,  276,  276,
      276,  277,  277,  276,  276,  276,  276,  276,  276,  276,
      279,  276,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  276,  279,  279,  278,

      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,

      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,    0,  276,  276,  276
    } ;

static yyconst short int yy_nxt[570] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       34,   35,   29,   29,   36,   29,   37,   38,   39,   29,
       40,   41,   42,   43,   44,   45,   46,   29,   29,   29,
       47,   48,   49,   50,   55,   62,   62,   62,   62,   62,
       62,   62,   56,   63,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   81,   62,   62,   66,   77,   73,   67,   62,   65,
       68,   69,   78,   64,   71,   84,   74,   80,   79,   75,

       70,   76,   92,   82,   89,   72,   83,   85,   86,   62,
       93,  100,   90,   62,   62,   94,  101,   87,   62,   91,
       88,   62,   62,   62,   62,   62,  105,   62,   62,   62,
       62,   95,   62,  102,  103,   62,   96,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
      104,   62,   62,  106,  110,   62,  118,  108,  107,  114,
      109,  111,  112,  113,  116,  119,  115,  117,  121,  122,
      120,  123,  124,  129,  125,  127,  131,  130,  132,  133,
      136,  135,  137,   62,   62,   62,   62,  134,   62,   62,
      128,  126,   62,   62,   62,   62,   62,   62,   62,   62,

       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
      138,   62,  139,   62,  145,  146,  141,   62,  140,  151,
      147,  149,   62,  142,  148,  143,  152,  155,  144,  153,
      154,   62,  156,   62,  150,  159,   62,  160,  161,  157,
      158,  164,   62,   62,   62,  163,  162,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,  165,
       62,   62,   62,   62,   62,   62,  169,  170,   62,  166,
      167,  175,  168,  174,  176,  172,   62,  171,   62,  177,
       62,   62,   62,  182,  184,  173,  180,   62,  178,  181,
      179,   62,  183,  192,  186,  187,   62,  188,  185,   62,

      189,  190,  191,   62,  193,   62,   62,   62,   62,   62,
       62,  196,   62,   62,   62,   62,   62,  194,  199,  195,
       62,   62,   62,   62,  197,  200,   62,  198,  201,   62,
       62,   62,  208,  203,   62,   62,  207,   62,  202,  209,
       62,   62,  210,  211,  206,  213,  204,  205,  212,   62,
      214,   62,  218,  215,  216,   62,  219,   62,   62,  221,
      222,   62,   62,  224,   62,  223,  217,   62,  220,   62,
       62,   62,   62,   62,   62,   62,   62,  231,  226,  227,
       62,  229,   62,   62,   62,   62,  225,   62,  235,  228,
      230,  232,  233,  236,   62,  234,  237,   62,  239,  241,

       62,  242,   62,   62,   62,   62,  243,  247,  238,   62,
      240,   62,   62,  244,  245,   62,  248,   62,   62,   62,
       62,   62,  246,   62,  250,   62,   62,  251,  255,   62,
       62,  249,   62,  254,   62,  252,  256,  258,  253,   62,
      262,  259,  260,  264,   62,  257,   62,   62,   62,  265,
       62,   62,   62,  261,   62,   62,   62,   62,  263,   62,
       62,  272,  266,  271,   62,  267,  273,  268,   62,  269,
       62,  270,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,  274,   62,  275,   52,   62,   52,   98,
       62,   98,   62,   62,   62,   99,   99,   62,   62,   99,

       58,   97,   53,   53,   62,   61,   60,   59,   58,   57,
       54,   53,   51,  276,    3,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276
    } ;

static yyconst short int yy_chk[570] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   15,   30,   31,   32,   33,   38,
       36,   39,   15,  278,   34,   37,   35,  275,   40,  270,
       44,   41,  269,  263,   64,  260,  259,   43,  256,  255,
       42,   39,   45,   65,   32,   36,   35,   32,   69,   31,
       32,   33,   36,   30,   34,   41,   35,   38,   37,   35,

       33,   35,   44,   40,   43,   34,   40,   42,   42,   46,
       45,   64,   43,   66,   67,   45,   65,   42,   68,   43,
       42,   70,   71,   72,   73,   81,   69,   75,   74,   78,
       80,   46,   79,   66,   67,   76,   46,   82,   90,   85,
      252,  249,  246,   84,   91,   88,   93,   83,   86,   89,
       68,   92,   94,   70,   73,   87,   81,   72,   71,   78,
       72,   74,   75,   76,   79,   82,   78,   80,   83,   84,
       82,   84,   85,   88,   86,   87,   90,   89,   91,   92,
       94,   93,   94,   95,   96,  100,  101,   92,  102,  103,
       87,   86,  104,  105,  108,  106,  107,  109,  110,  111,

      119,  114,  113,  120,  116,  121,  123,  117,  118,  122,
       95,  124,   96,  125,  105,  106,  101,  126,  100,  111,
      107,  109,  127,  102,  108,  103,  113,  117,  104,  114,
      116,  128,  118,  129,  110,  121,  130,  122,  123,  119,
      120,  126,  131,  132,  133,  125,  124,  134,  135,  139,
      136,  137,  143,  144,  138,  148,  145,  149,  146,  127,
      150,  151,  152,  153,  156,  159,  131,  132,  160,  128,
      129,  137,  130,  136,  138,  134,  155,  133,  158,  139,
      161,  157,  162,  148,  150,  135,  145,  163,  143,  146,
      144,  164,  149,  159,  152,  153,  166,  155,  151,  165,

      156,  157,  158,  167,  160,  170,  171,  172,  173,  176,
      175,  163,  177,  179,  181,  180,  183,  161,  166,  162,
      189,  182,  186,  188,  164,  167,  187,  165,  170,  190,
      191,  193,  179,  172,  192,  194,  177,  196,  171,  180,
      197,  198,  181,  182,  176,  186,  173,  175,  183,  199,
      187,  200,  191,  188,  189,  201,  192,  203,  206,  194,
      196,  204,  205,  198,  215,  197,  190,  211,  193,  208,
      210,  218,  217,  216,  220,  221,  227,  206,  200,  201,
      224,  204,  228,  229,  230,  231,  199,  232,  215,  203,
      205,  208,  210,  216,  234,  211,  217,  233,  220,  224,

      239,  227,  236,  238,  240,  243,  228,  232,  218,  247,
      221,  241,  245,  229,  230,  248,  233,  250,  253,  251,
      254,  257,  231,  258,  236,  261,  262,  238,  243,  264,
      265,  234,  266,  241,  267,  239,  245,  248,  240,  271,
      254,  250,  251,  258,  268,  247,  272,  273,  274,  261,
      244,  242,  237,  253,  235,  226,  225,  223,  257,  222,
      219,  271,  262,  268,  214,  264,  272,  265,  213,  266,
      212,  267,  209,  207,  202,  195,  185,  184,  178,  174,
      169,  168,  154,  273,  147,  274,  277,  142,  277,  279,
      141,  279,  140,  115,  112,   99,   98,   77,   63,   61,

       58,   57,   53,   52,   29,   25,   22,   19,   18,   16,
       13,    7,    6,    3,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 ".\\cpp_lex.y"
#define INITIAL 0
#line 2 ".\\cpp_lex.y"

#include "cpp_parse.tab.h"

#define PREFIX //pp_lloc.first_line = yylineno;

/*
void mygetc(char* buf, int& result, int max_size)
{
	int c = fgetc(yyin);
	if (c == '\\')
	{
		int c2 = fgetc(yyin);
		if (c2 == '\r')
		{
			c2 = fgetc(yyin);
			ATLASSERT(c2 == '\n');

			c = fgetc(yyin);
		}
		else
		{
			ungetc(c2, yyin);
		}
	}

	result = (c == EOF) ? YY_NULL : (buf[0] = c, 1);
}

#define YY_INPUT(buf,result,max_size) mygetc(buf, result, max_size)
*/

#line 678 "lex.cpp_.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 40 ".\\cpp_lex.y"


#line 832 "lex.cpp_.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 277 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 515 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 42 ".\\cpp_lex.y"
{	PREFIX
					cpp_lval.num = atol(yytext);
					return INTEGER_LITERAL;
				}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 47 ".\\cpp_lex.y"
{	PREFIX 
					cpp_lval.string_literal = strdup(yytext);
					return LSTRING_LITERAL;
				}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 52 ".\\cpp_lex.y"
{	PREFIX 
					cpp_lval.string_literal = strdup(yytext);
					return STRING_LITERAL;
				}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 57 ".\\cpp_lex.y"
{ return '\n'; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 59 ".\\cpp_lex.y"
{ PREFIX return THREE_DOTS; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 60 ".\\cpp_lex.y"
{ PREFIX return TWO_COLON; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 61 ".\\cpp_lex.y"
{ PREFIX return PLUSPLUS; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 62 ".\\cpp_lex.y"
{ PREFIX return MINUSMINUS; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 63 ".\\cpp_lex.y"
{ PREFIX return ARROW; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 64 ".\\cpp_lex.y"
{ PREFIX return EQUAL; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 65 ".\\cpp_lex.y"
{ PREFIX return NOT_EQUAL; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 66 ".\\cpp_lex.y"
{ PREFIX return '*'; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 67 ".\\cpp_lex.y"
{ PREFIX return '='; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 68 ".\\cpp_lex.y"
{ PREFIX return '>'; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 69 ".\\cpp_lex.y"
{ PREFIX return '<'; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 70 ".\\cpp_lex.y"
{ PREFIX return '-'; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 71 ".\\cpp_lex.y"
{ PREFIX return '!'; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 72 ".\\cpp_lex.y"
{ PREFIX return '~'; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 73 ".\\cpp_lex.y"
{ PREFIX return ','; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 74 ".\\cpp_lex.y"
{ PREFIX return '{'; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 75 ".\\cpp_lex.y"
{ PREFIX return '}'; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 76 ".\\cpp_lex.y"
{ PREFIX return ';'; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 77 ".\\cpp_lex.y"
{ PREFIX return '['; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 78 ".\\cpp_lex.y"
{ PREFIX return ']'; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 79 ".\\cpp_lex.y"
{ PREFIX return '('; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 80 ".\\cpp_lex.y"
{ PREFIX return ')'; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 81 ".\\cpp_lex.y"
{ PREFIX return '?'; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 82 ".\\cpp_lex.y"
{ PREFIX return ':'; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 83 ".\\cpp_lex.y"
{ PREFIX return '+'; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 84 ".\\cpp_lex.y"
{ PREFIX return '-'; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 85 ".\\cpp_lex.y"
{ PREFIX return '/'; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 86 ".\\cpp_lex.y"
{ PREFIX return '%'; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 87 ".\\cpp_lex.y"
{ PREFIX return '.'; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 88 ".\\cpp_lex.y"
{ PREFIX return '&'; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 89 ".\\cpp_lex.y"
{ PREFIX return '|'; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 90 ".\\cpp_lex.y"
{ PREFIX return '^'; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 92 ".\\cpp_lex.y"
{  PREFIX return CHAR_KW; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 93 ".\\cpp_lex.y"
{  PREFIX return WCHAR_T_KW; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 94 ".\\cpp_lex.y"
{  PREFIX return BOOL_KW; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 95 ".\\cpp_lex.y"
{  PREFIX return SHORT_KW; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 96 ".\\cpp_lex.y"
{  PREFIX return INT_KW; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 97 ".\\cpp_lex.y"
{  PREFIX return LONG_KW; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 98 ".\\cpp_lex.y"
{  PREFIX return SIGNED_KW; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 99 ".\\cpp_lex.y"
{  PREFIX return UNSIGNED_KW; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 100 ".\\cpp_lex.y"
{  PREFIX return FLOAT_KW; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 101 ".\\cpp_lex.y"
{  PREFIX return DOUBLE_KW; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 102 ".\\cpp_lex.y"
{  PREFIX return VOID_KW; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 104 ".\\cpp_lex.y"
{  PREFIX return STATIC_CAST_KW; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 105 ".\\cpp_lex.y"
{  PREFIX return REINTERPRET_CAST_KW; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 106 ".\\cpp_lex.y"
{  PREFIX return DYNAMIC_CAST_KW; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 107 ".\\cpp_lex.y"
{  PREFIX return CONST_CAST_KW; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 109 ".\\cpp_lex.y"
{  PREFIX return IF_KW; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 110 ".\\cpp_lex.y"
{  PREFIX return ELSE_KW; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 111 ".\\cpp_lex.y"
{  PREFIX return SWITCH_KW; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 112 ".\\cpp_lex.y"
{  PREFIX return FOR_KW; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 113 ".\\cpp_lex.y"
{  PREFIX return DO_KW; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 114 ".\\cpp_lex.y"
{  PREFIX return WHILE_KW; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 115 ".\\cpp_lex.y"
{  PREFIX return SIZEOF_KW; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 116 ".\\cpp_lex.y"
{  PREFIX return TYPEDEF_KW; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 117 ".\\cpp_lex.y"
{ PREFIX return CLASS_KW; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 118 ".\\cpp_lex.y"
{  PREFIX return STRUCT_KW; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 119 ".\\cpp_lex.y"
{  PREFIX return UNION_KW; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 121 ".\\cpp_lex.y"
{ PREFIX return 14;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 123 ".\\cpp_lex.y"
{ PREFIX return NAMESPACE_KW;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 124 ".\\cpp_lex.y"
{ PREFIX return EXTERN_KW;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 125 ".\\cpp_lex.y"
{ PREFIX return THIS_KW;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 126 ".\\cpp_lex.y"
{ PREFIX return PRIVATE_KW;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 127 ".\\cpp_lex.y"
{ PREFIX return PROTECTED_KW;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 128 ".\\cpp_lex.y"
{ PREFIX return PUBLIC_KW;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 129 ".\\cpp_lex.y"
{  PREFIX return AUTO_KW; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 130 ".\\cpp_lex.y"
{  PREFIX return REGISTER_KW; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 131 ".\\cpp_lex.y"
{  PREFIX return STATIC_KW; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 132 ".\\cpp_lex.y"
{  PREFIX return MUTABLE_KW; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 133 ".\\cpp_lex.y"
{  PREFIX return INLINE_KW; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 134 ".\\cpp_lex.y"
{  PREFIX return VIRTUAL_KW; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 135 ".\\cpp_lex.y"
{  PREFIX return EXPLICIT_KW; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 136 ".\\cpp_lex.y"
{  PREFIX return FRIEND_KW; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 137 ".\\cpp_lex.y"
{  PREFIX return TRUE_KW; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 138 ".\\cpp_lex.y"
{  PREFIX return FALSE_KW; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 140 ".\\cpp_lex.y"
{  PREFIX cpp_lval.id = strdup(yytext); return identifier;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 141 ".\\cpp_lex.y"
{  PREFIX cpp_lval.id = strdup(yytext); return identifier_lparen;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 143 ".\\cpp_lex.y"
ECHO;
	YY_BREAK
#line 1342 "lex.cpp_.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 277 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 277 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 276);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 143 ".\\cpp_lex.y"

