//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PageDesigner.rc
//
#define IDS_PROJNAME                    100
#define IDR_PAGEDESIGNER                100
#define IDD_ABOUTBOX                    100
#define IDR_LAYERSDLG                   102
#define IDR_PDRENDERER                  103
#define IDR_SWATCHESDLG                 104
#define IDR_NAVIGATORDLG                105
#define IDR_GRADIENTDLG                 106
#define IDR_STROKEDLG                   107
#define IDD_TEXTWRAPDLG                 108
#define IDB_SWATCHESLIST                109
#define IDR_SWATCHESLIST                110
#define IDR_COLORDLG                    111
#define IDB_GRADIENTEDIT                112
#define IDR_GRADIENTEDIT                113
#define IDR_TOOLSDLG                    114
#define IDD_NEWDOCUMENTDLG              115
#define IDD_PATHTYPEOPTIONSDLG          116
#define IDD_INSERTPAGESDLG              117
#define IDB_TABSCONTROL                 118
#define IDR_TABSCONTROL                 119
#define IDD_TEXTFRAMEOPTIONSDLG         120
#define IDR_TABSDLG                     121
#define IDD_PREFSUNITSDLG               122
#define IDD_PREFSGRIDSDLG               123
#define IDD_JUSTIFICATIONDLG            124
#define IDD_LAYEROPTIONSDLG             125
#define IDD_PAGESOPTIONSDLG             126
#define IDD_RECTANGLEOPTIONSDLG         127
#define IDR_PAGEDESIGNERFRAME           128
#define IDR_MAINFRAME                   128
#define IDR_PDDOCUMENTVIEW              129
#define IDD_ELLIPSEOPTIONSDLG           130
#define IDC_HAND0                       131
#define IDC_HAND2                       132
#define IDC_HAND1                       133
#define IDD_SECTIONOPTIONSDLG           134
#define IDD_COLORSWATCHOPTIONSDLG       135
#define IDD_GRADIENTSWATCHOPTIONSDLG    136
#define IDR_SWATCHLIBRARYDLG            137
#define IDD_TINTSWATCHOPTIONSDLG        138
#define IDD_DOCUMENTSETUPDLG            139
#define IDD_DROPCAPSDLG                 140
#define IDD_PARAGRAPHINDENTSDLG         141
#define IDD_BASICCHARACTERDLG           142
#define IDD_MASTEROPTIONSDLG            144
#define IDD_CREATEGUIDESDLG             145
#define IDD_MARGINSANDCOLUMNSDLG        146
#define IDD_ABOUTDLG                    147
#define IDD_BRUSHDIMENSIONSDLG          148
#define IDR_LINKSDLG                    149
#define IDD_LINKSOPTIONSDLG             150
#define IDD_RASTERIZEDLG                151
#define IDR_TRANSPARENCYDLG             152
#define IDR_FILTERGRAPHDLG              153
#define IDR_FEGAUSSIANBLUR              154
#define IDR_FEOFFSET                    155
#define IDR_FECOMPOSITE                 156
#define IDR_PLUGINFILTERSDLG            157
#define IDD_FEGAUSSIANBLURDLG           158
#define IDR_STYLESDLG                   159
#define IDR_FEFREETRANSFORM             160
#define IDD_PREFSTRANSPARENCYDLG        161
#define IDR_ARCHIVE                     162
#define IDD_PATTERNSWATCHOPTIONSDLG     163
#define IDR_SYMBOLSDLG                  164
#define IDR_PDSYMBOL                    165
#define IDR_PDOBJECTSYMBOLINSTANCE      166
#define IDD_SYMBOLOPTIONSDLG            167
#define IDR_PDOBJECTSYMBOLINSTANCESET   168
#define IDD_SVGEXPORTOPTIONSDLG         169
#define IDD_PREFSCLIPBOARDDLG           170
#define IDR_PAGESDLG                    202
#define IDB_VISIBLE                     203
#define IDB_LOCKED                      204
#define IDR_LAYERS                      205
#define IDR_PAGES                       206
#define IDR_PDMATRIX                    208
#define IDD_STROKEDLG                   209
#define IDR_SWATCHES                    210
#define IDC_SELECT                      211
#define IDC_DIRECT                      212
#define IDC_DIRECTPLUS                  213
#define IDC_ZOOMIN                      214
#define IDC_ZOOMOUT                     215
#define IDR_TEXTWRAPDLG                 216
#define IDR_PDGRADIENT                  217
#define IDR_TOOLS                       218
#define IDB_TEXTWRAP                    223
#define IDB_TEXTWRAP_TOP                224
#define IDB_TEXTWRAP_LEFT               225
#define IDB_TEXTWRAP_BOTTOM             226
#define IDB_TEXTWRAP_RIGHT              227
#define IDC_TEXTTEXTNS                  228
#define IDC_TEXTNEW                     229
#define IDC_TEXTTEXTEW                  230
#define IDC_TEXTTEXTNSEW                231
#define IDC_TEXTTEXTSN                  232
#define IDC_TEXTTEXTWE                  233
#define IDC_TEXTTEXTNSWE                234
#define IDR_PARAGRAPH                   234
#define IDC_TEXTTEXTSNWE                235
#define IDC_TEXTTEXTSNEW                236
#define IDC_PLACETEXT                   237
#define IDC_LINKTEXT                    238
#define IDC_TEXTPATH                    239
#define IDC_TEXTPATHPLUS                240
#define IDC_SIZE_WE                     241
#define IDC_SIZE_NS                     242
#define IDC_SIZE_NESW                   243
#define IDC_SIZE_NWSE                   244
#define IDC_MOVE                        245
#define IDC_ROTATE_N                    246
#define IDC_ROTATE_S                    247
#define IDC_ROTATE_E                    248
#define IDC_ROTATE_W                    249
#define IDC_ROTATE_NW                   250
#define IDC_ROTATE_NE                   251
#define IDC_ROTATE_SE                   252
#define IDC_ROTATE_SW                   253
#define IDC_SKEW_X                      254
#define IDC_SKEW_Y                      255
#define IDC_CROSSHAIR                   256
#define IDR_TEXTWRAP                    258
#define IDR_CHARACTER                   262
#define IDD_TABSDLG                     263
#define IDB_SWATCHES                    270
#define IDB_ACTIVELAYER                 272
#define IDB_TABS_POSITIONABOVEFRAME     274
#define IDB_ORIENTATION_PORTRAIT        275
#define IDB_ORIENTATION_LANDSCAPE       276
#define IDC_SELECTOVER                  277
#define IDC_DIRECTOVER                  278
#define IDC_PEN                         280
#define IDB_THUMBSIZE_SMALL             290
#define IDB_THUMBSIZE_MEDIUM            291
#define IDR_LINKS                       291
#define IDB_THUMBSIZE_LARGE             292
#define IDR_TRANSPARENCY                292
#define IDD_TRANSPARENCYDLG             293
#define IDR_PDCONTENTGRAPHIC            295
#define IDR_PDCONTENTTEXT               296
#define IDR_PDLAYER                     297
#define IDR_PDPAGE                      298
#define IDR_PDSPREADDOCUMENT            299
#define IDR_PDSPREADMASTER              300
#define IDR_PDOBJECTLAYERGROUP          302
#define IDR_PDOBJECTFRAME               303
#define IDR_PDFILTERPRIMITIVE           304
#define IDR_PDAPPEARANCE                305
#define IDR_PDFILL                      306
#define IDR_PDOBJECTFILL                306
#define IDR_PDSTROKE                    307
#define IDR_PDOBJECTSTROKE              307
#define IDR_PDSWATCHPATTERN             308
#define IDR_APPEARANCEDLG               309
#define IDR_APPEARANCE                  310
#define IDR_PDSWATCHCOLOR               311
#define IDR_PDSWATCHGRADIENT            312
#define IDR_PDGRADIENTSTOP              313
#define IDR_PDSWATCHNONE                314
#define IDC_PENCORNER                   315
#define IDR_PDOBJECTGROUP               315
#define IDR_SYMBOLS                     316
#define IDD_COLORDLG                    317
#define IDR_COLOR                       319
#define IDB_STROKE_CAP0                 320
#define IDB_STROKE_CAP1                 321
#define IDR_PDDOCUMENT                  321
#define IDB_STROKE_CAP2                 322
#define IDB_STROKE_JOIN0                323
#define IDB_STROKE_JOIN1                324
#define IDB_STROKE_JOIN2                325
#define IDB_OPACITYMASKLINKED           326
#define IDR_TABS                        327
#define IDB_TABS_ALIGNLEFT              328
#define IDB_TABS_ALIGNCENTER            329
#define IDR_NAVIGATOR                   329
#define IDC_PENDELETE                   330
#define IDB_TABS_ALIGNRIGHT             330
#define IDB_TABS_ALIGNDECIMAL           331
#define IDC_STROKE_WEIGHT               1006
#define IDC_NEWDOC_NUMBEROFPAGES        1007
#define IDC_TEXTWRAP_NONE               1008
#define IDC_TEXTWRAP_BBOX               1009
#define IDC_TEXTWRAP_SHAPE              1010
#define IDC_TEXTWRAP_OBJECT             1011
#define IDC_TEXTWRAP_COLUMN             1012
#define IDC_TEXTWRAP_TOP                1013
#define IDC_TEXTWRAP_BOTTOM             1014
#define IDC_NEWDOC_PAGEWIDTH            1014
#define IDC_TEXTWRAP_LEFT               1015
#define IDC_NEWDOC_PAGEHEIGHT           1015
#define IDC_PATHTYPE_ALIGN              1015
#define IDC_TEXTWRAP_RIGHT              1016
#define IDC_TEXTFRAME_IGNOREWRAP        1017
#define IDC_TABS                        1018
#define IDC_RULERUNITS_ORIGIN           1019
#define IDC_DOCUMENTGRID_HOREVERY       1020
#define IDC_DOCUMENTGRID_HORSUBDIVS     1021
#define IDC_DOCUMENTGRID_VEREVERY       1022
#define IDC_DOCUMENTGRID_VERSUBDIVS     1023
#define IDC_BASELINEGRID_START          1024
#define IDC_BASELINEGRID_INCREMENT      1025
#define IDC_WORDSPACING_MINIMUM         1026
#define IDC_WORDSPACING_DESIRED         1027
#define IDC_LAYER_NAME                  1027
#define IDC_WORDSPACING_MAXIMUM         1028
#define IDC_LAYER_SHOWLAYER             1028
#define IDC_LAYER_SHOWGUIDES            1029
#define IDC_LAYER_LOCKLAYER             1030
#define IDC_INSERTPAGES_PAGES           1030
#define IDC_LAYER_LOCKGUIDES            1031
#define IDC_INSERTPAGES_INSERT          1031
#define IDC_INSERTPAGES_INSERTNUMBER    1032
#define IDC_INSERTPAGES_MASTER          1033
#define IDC_PAGESOPTIONS_PAGESSIZE      1034
#define IDC_PAGESOPTIONS_MASTERSSIZE    1035
#define IDC_PAGESOPTIONS_LAYOUT_ONTOP   1036
#define IDC_PAGESOPTIONS_LAYOUT_ONTOP2  1037
#define IDC_PAGESOPTIONS_RESIZE         1038
#define IDC_OBJECT_WIDTH                1039
#define IDC_OBJECT_HEIGHT               1040
#define IDC_SECTIONOPTIONS_STARTSECTION 1040
#define IDC_SECTIONOPTIONS_PAGENUMBERING0 1041
#define IDC_SECTIONOPTIONS_PAGENUMBERING1 1042
#define IDC_SECTIONOPTIONS_PAGENUMBERING_STARTAT 1043
#define IDC_SECTIONOPTIONS_STYLE        1044
#define IDC_SWATCH_NAME                 1045
#define IDC_SWATCH_NAMEWITHCOLORVALUE   1046
#define IDC_SWATCH_COLORMODE            1047
#define IDC_SWATCH_CHANNELSLIDER0       1048
#define IDC_SWATCH_CHANNELSLIDER1       1049
#define IDC_SWATCH_CHANNELSLIDER2       1050
#define IDC_SWATCH_CHANNELSLIDER3       1051
#define IDC_SWATCH_CHANNELNAME0         1052
#define IDC_SWATCH_CHANNELNAME1         1053
#define IDC_SWATCH_CHANNELNAME2         1054
#define IDC_SWATCH_CHANNELNAME3         1055
#define IDC_SWATCH_COLORSLIDERS         1056
#define IDC_SWATCH_CHANNELVALUE0        1057
#define IDC_SWATCH_CHANNELVALUE1        1058
#define IDC_SWATCH_CHANNELVALUE2        1059
#define IDC_SWATCH_CHANNELVALUE3        1060
#define IDC_SWATCH_NAMEWITHCOLORVALUENAME 1061
#define IDC_SWATCH_COLORTYPE            1062
#define IDC_SWATCH_NAMEDCOLORS          1063
#define IDC_SWATCH_GRADIENT             1064
#define IDC_SWATCH_GRADIENTTYPE         1065
#define IDC_SWATCH_LOCATION             1066
#define IDC_TEXTFRAME_COLUMNS_NUMBER    1067
#define IDC_TEXTFRAME_COLUMNS_GUTTER    1068
#define IDC_TABS_POSITIONABOVEFRAME     1068
#define IDC_TEXTFRAME_INSET_TOP         1069
#define IDC_TEXTFRAME_INSET_BOTTOM      1070
#define IDC_TEXTFRAME_INSET_RIGHT       1071
#define IDC_TEXTFRAME_INSET_LEFT        1072
#define IDC_NEWDOC_FACINGPAGES          1072
#define IDC_NEWDOC_MASTERTEXTFRAME      1073
#define IDC_NEWDOC_MARGINS_LEFTTEXT     1074
#define IDC_NEWDOC_MARGINS_RIGHTTEXT    1075
#define IDC_NEWDOC_MARGINS_TOP          1076
#define IDC_NEWDOC_MARGINS_BOTTOM       1077
#define IDC_NEWDOC_MARGINS_LEFT         1078
#define IDC_NEWDOC_MARGINS_RIGHT        1079
#define IDC_NEWDOC_COLUMNS_NUMBER       1080
#define IDC_NEWDOC_COLUMNS_GUTTER       1081
#define IDC_NEWDOC_PAGESIZE_PRESETS     1082
#define IDC_NEWDOC_ORIENTATION_PORTRAIT 1083
#define IDC_NEWDOC_ORIENTATION_LANDSCAPE 1084
#define IDC_DROPCAPS_LINES              1085
#define IDC_DROPCAPS_CHARACTERS         1086
#define IDC_PARAGRAPHINDENTS_ALIGNMENT  1086
#define IDC_PARAGRAPHINDENTS_LEFTINDENT 1087
#define IDC_PARAGRAPHINDENTS_FIRSTLINEINDENT 1088
#define IDC_PARAGRAPHINDENTS_RIGHTINDENT 1089
#define IDC_RULERUNITS_HORIZONTAL       1089
#define IDC_PARAGRAPHINDENTS_SPACEBEFORE 1090
#define IDC_RULERUNITS_VERTICAL         1090
#define IDC_CHARACTER_FONT              1090
#define IDC_CHARACTER_SIZE              1091
#define IDC_MASTER_PREFIX               1091
#define IDC_PARAGRAPHINDENTS_SPACEAFTER 1092
#define IDC_MASTER_NAME                 1092
#define IDC_MASTER_NUMPAGES             1094
#define IDC_MASTER_BASEDON              1095
#define IDC_CREATEGUIDES_ROWSNUM        1096
#define IDC_CREATEGUIDES_ROWSGUTTER     1097
#define IDC_CREATEGUIDES_COLSNUM        1098
#define IDC_CREATEGUIDES_COLSGUTTER     1099
#define IDC_CREATEGUIDES_FIT0           1100
#define IDC_CREATEGUIDES_FIT1           1101
#define IDC_CREATEGUIDES_REMOVEEXISTING 1102
#define IDC_BRUSH_WIDTH                 1110
#define IDC_BRUSH_HEIGHT                1112
#define IDC_BRUSH_ANGLE                 1113
#define IDC_BRUSH_SHOW                  1114
#define IDC_BRUSH_TIP                   1115
#define IDC_LINKSOPTIONS_THUMB_NONE     1116
#define IDC_LINKSOPTIONS_THUMB_SMALL    1117
#define IDC_RASTERIZE_RES_SCREEN        1117
#define IDC_RASTERIZE_RES72             1117
#define IDC_LINKSOPTIONS_THUMB_MEDIUM   1118
#define IDC_RASTERIZE_RES_SCREEN2       1118
#define IDC_RASTERIZE_RES150            1118
#define IDC_LINKSOPTIONS_THUMB_LARGE    1119
#define IDC_RASTERIZE_RES_HIGH          1119
#define IDC_RASTERIZE_RES300            1119
#define IDC_RASTERIZE_RES_OTHER         1120
#define IDC_RASTERIZE_RES_DODUMENT      1121
#define IDC_RASTERIZE_RES_OTHERVALUE    1122
#define IDC_TRANSP_CLIP                 1123
#define IDC_TRANSP_INVERT               1124
#define IDC_FEGAUSSBLUR_DEVX            1124
#define IDC_FEGAUSSBLUR_DEVY            1125
#define IDC_PREFSTRANSP_GRIDSIZE        1125
#define IDC_PREFSTRANSP_GRIDCOLORS      1126
#define IDC_STROKE_DASHED0              1128
#define IDC_STROKE_DASHED1              1129
#define IDC_TRANSP_OPACITY              1129
#define IDC_STROKE_DASHED2              1130
#define IDC_SYMBOL_NAME                 1130
#define IDC_STROKE_DASHED3              1131
#define IDC_SVG_IMAGESEMBED             1131
#define IDC_STROKE_DASHED4              1132
#define IDC_SVG_IMAGESLINK              1132
#define IDC_STROKE_DASHED5              1133
#define IDC_STROKE_CAP0                 1134
#define IDC_STROKE_CAP1                 1135
#define IDC_STROKE_CAP2                 1136
#define IDC_STROKE_JOIN0                1137
#define IDC_STROKE_JOIN1                1138
#define IDC_STROKE_JOIN2                1139
#define IDC_STROKE_MITERLIMIT           1140
#define IDC_TRANSP_THUMBNAIL            1141
#define IDC_RASTERIZE_BG0               1142
#define IDC_RASTERIZE_BG1               1143
#define IDC_TABS_ALIGNLEFT              1147
#define IDC_TABS_ALIGNCENTER            1148
#define IDC_TABS_ALIGNRIGHT             1149
#define IDC_TABS_ALIGNDECIMAL           1150
#define IDC_TABS_X                      1153
#define IDC_TABS_LEADER                 1154
#define IDC_CLIPBOARD_PNG               1156
#define IDC_CLIPBOARD_JPEG              1157
#define IDC_CLIPBOARD_GIF               1158
#define IDC_TEXTFRAME_COLUMNS_WIDTH     1160
#define IDC_TEXTFRAME_COLUMNS_FIXEDWIDTH 1161
#define IDC_COLOR_NONE                  1163
#define IDC_COLOR_SPECTRUM              1164
#define IDC_PENADD                      10010
#define IDC_PENNEW                      10011
#define IDC_PENCLOSE                    10012
#define IDC_PENCONTINUE                 10013
#define IDC_PENCHANGELAST               10014
#define IDC_PENCONNECT                  10015
#define IDC_PLACEGRAPHICNEW             10016
#define IDC_PLACEGRAPHICOVER            10017
#define ID_VIEW_ZOOMIN                  32772
#define ID_VIEW_ZOOMOUT                 32773
#define ID_FILE_CUSTOMIZE               32774
#define ID_FILE_DOCUMENTSETUP           32775
#define ID_OBJECT_CONTENT_GRAPHIC       32776
#define ID_OBJECT_CONTENT_TEXT          32777
#define ID_OBJECT_CONTENT_UNASSIGNED    32778
#define ID_FILE_PLACE                   32779
#define ID_TOOL_SELECT                  32780
#define ID_TOOL_DIRECT                  32781
#define ID_TOOL_ELLIPSE                 32782
#define ID_TOOL_RECTANGLE               32783
#define ID_TOOL_ELLIPSEGRAPHIC          32784
#define ID_TOOL_RECTANGLEGRAPHIC        32785
#define ID_TOOL_TEXTPATH                32786
#define ID_TOOL_TEXT                    32787
#define ID_TOOL_ZOOM                    32788
#define ID_LAYERS_NEWLAYER              32789
#define ID_LAYERS_LAYEROPTIONS          32790
#define ID_PAGES_INSERTPAGES            32791
#define ID_PAGES_NEWMASTER              32792
#define ID_PAGES_KEEPSPREADTOGETHER     32793
#define ID_PAGES_ALLOWPAGESTOSHUFFLE    32794
#define ID_TOOL_SCALE                   32795
#define ID_TOOL_ROTATE                  32797
#define ID_VIEW_RULERS                  32799
#define ID_VIEW_ACTUALSIZE              32800
#define ID_TOOL_HAND                    32801
#define ID_TOOL_PATHPEN                 32802
#define ID_TOOL_PATHADDANCHOR           32803
#define ID_TOOL_PATHDELETEANCHOR        32804
#define ID_TOOL_PATHCORNER              32805
#define ID_OBJECT_GROUP                 32806
#define ID_OBJECT_UNGROUP               32807
#define ID_OBJECT_LOCKPOSITION          32808
#define ID_OBJECT_UNLOCKPOSITION        32809
#define ID_OBJECT_COMPOUNDPATHS_MAKE    32810
#define ID_OBJECT_COMPOUNDPATHS_RELEASE 32811
#define ID_OBJECT_REVERSEPATH           32812
#define ID_SWATCHES_NEWCOLORSWATCH      32813
#define ID_SWATCHES_NEWGRADIENTSWATCH   32814
#define ID_SWATCHES_NEWTINTSWATCH       32815
#define ID_OBJECT_FITTING_FITCONTENTTOFRAME 32816
#define ID_OBJECT_FITTING_FITFRAMETOCONTENT 32817
#define ID_OBJECT_FITTING_CENTERCONTENT 32818
#define ID_OBJECT_FITTING_FITCONTENTPROPORTIONALLY 32819
#define ID_TOOL_GRADIENT                32820
#define ID_TYPE_FONTFACE                32823
#define ID_PARAGRAPH_ALIGNLEFT          32824
#define ID_PARAGRAPH_ALIGNCENTER        32825
#define ID_PARAGRAPH_ALIGNRIGHT         32826
#define ID_PARAGRAPH_JUSTIFYLEFT        32827
#define ID_PARAGRAPH_JUSTIFYCENTER      32828
#define ID_PARAGRAPH_JUSTIFYRIGHT       32829
#define ID_PARAGRAPH_JUSTIFYALL         32830
#define ID_OBJECT_PATHTYPE_OPTIONS      32837
#define ID_OBJECT_PATHTYPE_DELETE       32838
#define ID_TOOL_FREETRANSFORM           32839
#define ID_TOOL_LINE                    32842
#define ID_EDIT_PASTEINTO               32843
#define ID_TEXTWRAP_NONE                32844
#define ID_TEXTWRAP_BBOX                32845
#define ID_TEXTWRAP_SHAPE               32846
#define ID_TEXTWRAP_OBJECT              32847
#define ID_TEXTWRAP_COLUMN              32848
#define ID_TYPE_CREATEOUTLINES          32849
#define ID_OBJECT_TEXTFRAMEOPTIONS      32850
#define ID_EDIT_PREFERENCES             32851
#define ID_VIEW_DOCUMENTGRID            32852
#define ID_VIEW_BASELINEGRID            32853
#define ID_PAGES_PALETTEOPTIONS         32861
#define ID_PAGES_SECTIONOPTIONS         32862
#define ID_EDIT_DOCUMENTCOLORSETTINGS   32863
#define ID_SWATCHES_DELETESWATCH        32864
#define ID_SWATCHES_SWATCHOPTIONS       32865
#define ID_LAYERS_DELETE                32866
#define ID_TYPE_PARAGRAPH               32867
#define ID_TYPE_CHARACTER               32868
#define ID_PAGES_MASTEROPTIONS          32869
#define ID_LAYOUT_CREATEGUIDES          32870
#define ID_LAYOUT_MARGINSANDCOLUMNS     32871
#define ID_OBJECT_PATH_ADDANCHORPOINTS  32875
#define ID_CHARACTER_FONTSIZE           32876
#define ID_CHARACTER_BOLD               32878
#define ID_CHARACTER_ITALIC             32879
#define ID_CHARACTER_UNDERLINE          32880
#define ID_CHARACTER_LINEHEIGHT         32881
#define ID_TYPE_SHOWHIDDENCHARACTERS    32882
#define ID_TOOL_BULGE                   32884
#define ID_TOOL_TWIRL                   32885
#define ID_LINKS_PALETTEOPTIONS         32886
#define ID_OBJECT_RASTERIZE             32887
#define ID_TRANSPARENCY_MAKEOPACITYMASK 32888
#define ID_TRANSPARENCY_RELEASEOPACITYMASK 32889
#define ID_VIEW_TRANSPARENCYGRID        32890
#define ID_EDIT_DEFINEPATTERN           32891
#define ID_APPEARANCE_ADDNEWSTROKE      32892
#define ID_APPEARANCE_ADDNEWFILL        32893
#define ID_OBJECT_ARRANGE_BRINGTOFRONT  32894
#define ID_OBJECT_ARRANGE_BRINGFORWARD  32895
#define ID_OBJECT_ARRANGE_SENDBACKWARD  32896
#define ID_OBJECT_ARRANGE_SENDTOBACK    32897
#define ID_FILE_EXPORT_SVG              32898
#define ID_SYMBOLS_NEWSYMBOL            32899
#define ID_SYMBOLS_PLACESYMBOLINSTANCE  32900
#define ID_TOOL_SYMBOLSPRAYER           32901
#define ID_SYMBOLS_BREAKLINKTOSYMBOL    32902
#define ID_SYMBOLS_REDEFINESYMBOL       32903
#define ID_SYMBOLS_SYMBOLOPTIONS        32904
#define ID_COLOR_RGB                    32905
#define ID_COLOR_ADDTOSWATCHES          32906
#define ID_COLOR_GRAYSCALE              32907
#define ID_COLOR_HSB                    32908
#define ID_FILE_EXPORT_PDF              32909
#define ID_TEXTWRAP_TOPOFFSET           32910
#define ID_TEXTWRAP_LEFTOFFSET          32911
#define ID_TEXTWRAP_BOTTOMOFFSET        32912
#define ID_TEXTWRAP_RIGHTOFFSET         32913
#define ID_TRANSPARENCY_ENABLEOPACITYMASK 32914
#define ID_TRANSPARENCY_LINKOPACITYMASK 32915
#define ID_PAGES_COPY                   32916
#define ID_TABS_CLEARALL                32917
#define ID_NAVIGATOR_VIEWALLSPREADS     32922
#define ID_VIEW_SHOWTEXTTHREADS         32923
#define ID_APPEARANCE_NEWARTHASBASICAPPEARANCE 32924
#define ID_APPEARANCE_REMOVEITEM        32925
#define ID_APPEARANCE_REDUCETOBASICAPPEARANCE 32926

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        330
#define _APS_NEXT_COMMAND_VALUE         32927
#define _APS_NEXT_CONTROL_VALUE         1165
#define _APS_NEXT_SYMED_VALUE           171
#endif
#endif
