//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by LXMLEditor.rc
//
#define IDS_PROJNAME                    100
#define IDB_CSSSTYLESHEETVIEWCTL        102
#define IDR_CSSSTYLESHEETVIEWCTL        103
#define IDD_FILENEWDLG                  104
#define IDD_NITFTOPICSDLG               105
#define IDD_FILESAVETEXTOPTIONSDLG      106
#define IDD_TIMELISTDLG                 107
#define IDD_HSLCOLORWHEELDLG            108
#define IDD_AVAILABLECSSPROPERTIESDLG   109
#define IDD_PREFSSOURCEDLG              110
#define IDR_EASDOCUMENT                 111
#define IDD_TOOLPRESETNAMEDLG           112
#define IDD_SMILTIMEDLG                 114
#define IDD_LAYOUTVIEWOPTIONSDLG        115
#define IDR_ESCENEDOCUMENT              116
#define IDR_XMLGRIDVIEW                 128
#define IDC_HAND0                       131
#define IDC_HAND2                       132
#define IDC_HAND1                       133
#define IDR_EDITFILTERDLG               137
#define IDB_EDITFILTERGRAPH             138
#define IDB_DTDGRAPHCTL                 147
#define IDD_BRUSHDIMENSIONSDLG          148
#define IDR_SVGTOOLS                    156
#define IDR_CSSSTYLESHEETVIEW           159
#define IDD_PREFSTRANSPARENCYDLG        161
#define IDR_TEXTVIEW                    176
#define IDD_ASSIGNXSLDLG                181
#define IDD_OPENURLDLG                  189
#define IDR_SVGFILTERSDLG               198
#define IDR_SVGFILTERLIBRARYDLG         199
#define IDD_SVGFILTEROPTIONSDLG         200
#define IDR_EDITFILTERGRAPH             202
#define IDC_FILESAVE_CBENCODING         202
#define IDC_FILESAVE_STENCODING         203
#define IDR_ETEXTDOCUMENT               204
#define IDB_SCHEMADESIGN                204
#define IDC_TIME_LIST                   204
#define IDC_RESIZECOLUMN                204
#define IDR_EXTSCRIPTDOCUMENT           205
#define IDB_EXPANDED                    205
#define IDR_ESCRIPTDOCUMENT             205
#define IDC_COLORWHEEL                  205
#define IDR_WEBXMLDOCUMENT              206
#define IDR_EXMLDOCUMENT                206
#define IDC_HSL_HUE                     206
#define IDR_PATHEDITPLUGIN              207
#define IDC_HSL_SAT                     207
#define IDC_CSSCATEGORY                 207
#define IDB_SCRIPTOUTLINE               208
#define IDC_HSL_LUM                     208
#define IDC_CSSPROPERTY                 208
#define IDR_SELECTIONTOOLPLUGIN         209
#define IDC_FONT_SIZE                   209
#define IDR_TRANSFORMTOOLPLUGIN         210
#define IDC_NITF_TITLE                  210
#define IDR_MAINFRAME                   210
#define IDC_CSSPROPERTY_INFO            210
#define IDR_BASICSHAPETOOLPLUGIN        211
#define IDR_ASGRAPH                     211
#define IDC_NITF_SUBJECTS               211
#define IDC_SELECT                      211
#define IDC_SOURCE_COLOR_HEX3           211
#define IDR_TRANSITIONDIRECTIONUI       212
#define IDC_DIRECT                      212
#define IDC_SOURCE_COLOR_HEX6           212
#define IDR_XMLSOURCEVIEW               213
#define IDC_DIRECTPLUS                  213
#define IDR_LIQUIFYTOOLPLUGIN           213
#define IDB_PAINT                       213
#define IDC_SOURCE_RGB                  213
#define IDC_ZOOMIN                      214
#define IDR_ECSSDOCUMENT                214
#define IDC_SOURCE_RGBPERCENT           214
#define IDC_ZOOMOUT                     215
#define IDR_LXMLEDITORAPP               215
#define IDC_COLOR_ALPHASLIDER           215
#define IDR_TRANSITIONPROGRESSIONUI     216
#define IDC_COLOR_ALPHAVALUE            216
#define IDR_SVGGRADIENTEDITCTL          217
#define IDC_PATHSEG_ABSOLUTE            218
#define IDR_SYMBOLISMTOOLPLUGIN         219
#define IDC_PATHSEG_RELATIVE            219
#define IDD_STYLEFONTDLG                220
#define IDR_DTDDOCUMENT                 220
#define IDR_EDTDDOCUMENT                220
#define IDC_NAME                        220
#define IDR_XMLLAYOUTVIEW               221
#define IDC_SVGELLIPSE_CX               221
#define IDR_NEWSITEMDOCUMENT            221
#define IDD_NITFHEADDLG                 222
#define IDC_SVGELLIPSE_CY               222
#define IDC_SVGELLIPSE_RX               223
#define IDR_SMILTRANSITIONSDLG          223
#define IDC_SVGELLIPSE_RY               224
#define IDD_SVGELLIPSEDLG               225
#define IDB_SMALLBUTTONS                225
#define IDC_TIME_TYPE_OFFSET            225
#define IDC_TIME_TYPE_SYNCBASED         226
#define IDB_CSSIMPORTANT                227
#define IDC_TIME_OFFSET                 227
#define IDC_XSLTFOREACH_SELECT          228
#define IDC_TEXTTEXTNS                  228
#define IDC_TIME_TYPE_EVENTBASED        228
#define IDR_SCHEMAVIEW                  229
#define IDC_XSLTAPPLYTEMPLATES_MODE     229
#define IDC_TEXTNEW                     229
#define IDC_TIME_BASE                   229
#define IDC_XSLTAPPLYTEMPLATES_SELECT   230
#define IDD_XSLTFOREACHDLG              230
#define IDC_TEXTTEXTEW                  230
#define IDR_SCRIPTSDLG                  230
#define IDC_TIME_TYPE_INDEFINITE        230
#define IDD_XSLTAPPLYTEMPLATESDLG       231
#define IDC_XSLTTEMPLATE_MATCH          231
#define IDC_TEXTTEXTNSEW                231
#define IDR_XMLDOCUMENT                 231
#define IDC_LAYER_ISLAYER               231
#define IDC_ASSIGNXSL_FILE              232
#define IDD_XSLTTEMPLATEDLG             232
#define IDC_TEXTTEXTSN                  232
#define IDR_STYLESHEETSDLG              232
#define IDC_RULER_HORIZONTAL_UNITS      232
#define IDC_ASSIGNXSL_BROWSE            233
#define IDC_TEXTTEXTWE                  233
#define IDB_ASTREEICONS                 233
#define IDR_STYLERTOOLPLUGIN            233
#define IDC_RULER_VERTICAL_UNITS        233
#define IDC_SCROLLBAR1                  233
#define IDR_ASTREEVIEW                  234
#define IDC_TEXTTEXTNSWE                234
#define IDC_OPEN_URL                    234
#define IDR_XMLPREVIEWVIEW              235
#define IDC_TEXTTEXTSNWE                235
#define IDR_XSLTEMPLATESVIEW            236
#define IDC_SVGFEPOINTLIGHT_Z           236
#define IDC_TEXTTEXTSNEW                236
#define IDR_STYLERTOOLS                 236
#define IDC_SVGFEPOINTLIGHT_X           237
#define IDC_SVGFEPOINTLIGHT_Y           238
#define IDB_SEGTYPES                    238
#define IDC_UIPOINTLIGHT                239
#define IDC_TEXTPATH                    239
#define IDD_PATHTOOLOPTIONSDLG          239
#define IDD_SVGFEPOINTLIGHTDLG          240
#define IDC_TEXTPATHPLUS                240
#define IDR_TOOLPRESETSDLG              240
#define IDC_SIZE_WE                     241
#define IDC_SIZE_NS                     242
#define IDR_SEGTYPE                     242
#define IDC_SVGFECOMPOSITE_IN           243
#define IDD_SVGFILTERDLG                243
#define IDC_SIZE_NESW                   243
#define IDR_X3DVIEW                     243
#define IDC_SVGFECOMPOSITE_IN2          244
#define IDD_SVGFECOMPOSITEDLG           244
#define IDC_SIZE_NWSE                   244
#define IDC_SVGFE_RESULT                245
#define IDD_SVGLINEARGRADIENTDLG        245
#define IDC_SELECT_SELECTED             245
#define IDC_SVGFILTER_FILTERUNITS       246
#define IDC_ROTATE_N                    246
#define IDC_SVGFILTER_X                 247
#define IDD_SVGFEFLOODDLG               248
#define IDC_SVGFILTER_Y                 248
#define IDC_ID                          248
#define IDC_ROTATE_E                    248
#define IDR_SYMBOLSDLG                  249
#define IDC_SVGFEFLOOD_OPACITY          249
#define IDC_SVGFILTER_WIDTH             249
#define IDC_ROTATE_W                    249
#define IDR_SVGSYMBOLSDLG               249
#define IDC_SVGFILTER_HEIGHT            250
#define IDC_ROTATE_NW                   250
#define IDC_TABS_TABSIZE                250
#define IDC_ROTATE_NE                   251
#define IDD_PREFSTABSDLG                251
#define IDC_SMILANIMATE_FROM            252
#define IDD_SMILANIMATEDLG              252
#define IDC_ROTATE_SE                   252
#define IDR_SVGSWATCHESDLG              253
#define IDC_SMILANIMATE_TO              253
#define IDC_ROTATE_SW                   253
#define IDR_SVGSWATCHLIBRARYDLG         254
#define IDC_SMILANIMATE_BY              254
#define IDD_SVGANIMATETRANSFORMDLG      254
#define IDC_SKEW_X                      254
#define IDC_SMILANIMATE_TYPE            255
#define IDC_SKEW_Y                      255
#define IDR_PATHTOOLS                   255
#define IDC_SMILANIMATE_CALCMODE        256
#define IDC_HTMLFRAME_SIZEUNIT          257
#define IDD_HTMLFRAMEDLG                257
#define IDC_HTMLFRAME_SIZE              258
#define IDD_HTMLFRAMESETDLG             258
#define IDR_FRAMESDESIGNVIEW            259
#define IDC_HTMLFRAME_NAME              259
#define IDC_HTMLFRAME_SRC               260
#define IDD_COLORDLG                    260
#define IDC_HTMLFRAMESET_ORIENTATION0   261
#define IDC_HTMLFRAMESET_ORIENTATION1   262
#define IDC_HTMLFRAMESET_ORIENTATION2   263
#define IDC_HTMLFRAMESET_BORDERCOLOR    264
#define IDC_HTMLFRAME_SCROLLING         266
#define IDC_HTMLFRAME_NORESIZE          267
#define IDR_TRANSFORMTOOLS              267
#define IDC_HTMLFRAMESET_FRAMESPACING   268
#define IDC_HTMLFRAMESET_FRAMESPACINGVALUE 269
#define IDR_SELECTTOOLS                 269
#define IDC_COLOR_CHANNELSLIDER0        270
#define IDC_HTMLFRAMESET_BORDERCOLORVALUE 271
#define IDR_BASICSHAPETOOLS             271
#define IDC_COLOR_CHANNELSLIDER1        271
#define IDC_COLOR_CHANNELSLIDER2        272
#define IDC_SVGANIMATEMOTION_ROTATE     273
#define IDD_SVGANIMATEMOTIONDLG         273
#define IDD_SMILREGIONDLG               274
#define IDC_SMILROOTLAYOUT_WIDTH        274
#define IDC_SMILROOTLAYOUT_HEIGHT       275
#define IDD_SMILROOTLAYOUTDLG           275
#define IDC_SMILREGION_LEFT             276
#define IDD_SMILTOPLAYOUTDLG            276
#define IDC_SMILREGION_TOP              277
#define IDC_TIMEGRAPH_SIZE0             277
#define IDC_SELECT_UNSELECTED           277
#define IDC_SMILREGION_RIGHT            278
#define IDC_TIMEGRAPH_SIZE1             278
#define IDC_DIRECT_SELECTED             278
#define IDD_SMILANIMATECOLORDLG         279
#define IDC_SMILREGION_BOTTOM           279
#define IDC_TIMEGRAPH_SIZE2             279
#define IDR_SMILLAYOUTSDLG              280
#define IDC_SMILREGION_WIDTH            280
#define IDC_TIMEGRAPH_FORMAT0           280
#define IDD_SMILTIMEGRAPHOPTIONSDLG     280
#define IDC_PEN                         280
#define IDC_SMILMEDIA_SRC               281
#define IDC_SMILREGION_HEIGHT           281
#define IDC_TIMEGRAPH_FORMAT1           281
#define IDB_TIMEGRAPH_SIZE0             281
#define IDR_SMILTIMEGRAPHPOPUP          282
#define IDC_SMILMEDIA_ERASE             282
#define IDC_TIMEGRAPH_FORMAT2           282
#define IDB_TIMEGRAPH_SIZE1             282
#define IDC_SMILREGION_BACKGROUNDCOLORVALUE 283
#define IDC_TIMEGRAPH_FORMAT3           283
#define IDB_TIMEGRAPH_SIZE2             283
#define IDC_SMILREGION_FIT              284
#define IDB_TIMEGRAPH_FORMAT0           284
#define IDD_SMILMEDIADLG                285
#define IDC_SMILREGION_ZINDEX           285
#define IDB_TIMEGRAPH_FORMAT1           285
#define IDC_SMILREGION_SHOWBACKGROUND   286
#define IDD_SMILTRANSITIONDLG           286
#define IDB_TIMEGRAPH_FORMAT2           286
#define IDR_TIMEGRAPHVIEW               287
#define IDC_SMILTRANSITION_TYPE         287
#define IDB_TIMEGRAPH_FORMAT3           287
#define IDC_SMILTRANSITION_HORZREPEAT   289
#define IDC_SMILTRANSITION_VERTREPEAT   290
#define IDC_SMILTRANSITION_BORDERWIDTH  291
#define IDC_SMILTRANSITION_SETTINGS     292
#define IDC_SMILTRANSITION_DIRECTIONUI  293
#define IDD_TRANSITIONSETTINGSDLG       293
#define IDC_PREFSFORMAT_WINDOW          294
#define IDC_PREFSFORMAT_FONTFACE        295
#define IDB_BITMAPB                     296
#define IDC_PREFSFORMAT_FONTSIZE        296
#define IDB_BITMAPA                     297
#define IDC_PREFSFORMAT_COLORS          297
#define IDC_PREFSFORMAT_FGCOLOR         298
#define IDD_PREFSFORMATDLG              298
#define IDB_TT                          299
#define IDC_PREFSFORMAT_BGCOLOR         299
#define IDD_XPATHQUERYDLG               303
#define IDR_STANDARD                    304
#define IDC_SMILTRANSITION_STARTPROGRESSUI 308
#define IDC_SMILTRANSITION_ENDPROGRESSUI 309
#define IDC_XPATH_EXPR                  309
#define IDR_HTMLFORMATTING              310
#define IDC_XPATH_RESULT                310
#define IDC_XPATH_EVALUATE              311
#define IDR_FORMATTING                  311
#define IDC_TABLE_ROWS                  312
#define IDC_TABLE_COLUMNS               313
#define IDC_NAV_COLORLIST               314
#define IDR_INSERT                      314
#define IDR_CSSPROPERTIESDLG            315
#define IDC_NAV_COLOR                   315
#define IDC_PENCORNER                   315
#define IDC_SWATCH_CHANNELVALUE0        316
#define IDD_INSERTTABLEDLG              316
#define IDR_SVGELEMENTMASKDLG           317
#define IDC_BRUSH_EDITPROFILE           317
#define IDC_SWATCH_CHANNELVALUE1        317
#define IDB_STROKECAP                   318
#define IDC_SWATCH_CHANNELVALUE2        318
#define IDC_GLYPH_UNICODE               319
#define IDB_STROKEJOIN                  319
#define IDB_TEXTALIGN                   320
#define IDC_LAYER_COLORLIST             320
#define IDR_SVGOBJECTSDLG               321
#define IDC_LAYER_COLOR                 321
#define IDC_RECTGRID_HORZDIVS           322
#define IDD_NAVIGATOROPTIONSDLG         323
#define IDC_RECTGRID_VERTDIVS           323
#define IDC_RECTGRID_HORZSKEW           324
#define IDC_RECTGRID_VERTSKEW           325
#define IDB_FILLRULE                    325
#define IDC_RECTGRID_OUTSIDEASRECT      326
#define IDB_MASKLINKED                  326
#define IDC_POLARGRID_CONCENTRICDIVS    327
#define IDD_LAYEROPTIONSDLG             327
#define IDC_POLARGRID_CONCENTRICSKEW    328
#define IDC_ROTATE_S                    328
#define IDC_POLARGRID_RADIALDIVS        329
#define IDC_DIRECT_SELECTEDANCHOR       329
#define IDB_VISIBLE                     329
#define IDR_NAVIGATORDLG                330
#define IDC_POLARGRID_RADIALSKEW        330
#define IDC_DIRECT_SELECTEDSEGMENT      330
#define IDC_DIRECT_SELECTEDCONTROL      331
#define IDB_CSSSTYLESHEETS              331
#define IDC_GRADIENT_TYPE               333
#define IDR_LAYOUTNOSEL                 333
#define IDC_SVGGRADIENT                 334
#define IDR_LIQUIFYTOOLS                334
#define IDR_LAYOUTSEL                   334
#define IDR_COLORDLG                    336
#define IDR_SYMBOLISMTOOLS              337
#define IDD_BRUSHPROFILEDLG             338
#define IDC_CROSSHAIR                   339
#define IDR_SVGMASKSDLG                 340
#define IDR_SVGFONTGLYPHSDLG            343
#define IDR_SVGFONTSDLG                 344
#define IDR_DTDGRIDVIEW                 345
#define IDD_SVGGLYPHOPTIONSDLG          345
#define IDC_SMILTRANSITION_FR           345
#define IDR_CSSSOURCEVIEW               346
#define IDD_RECTANGULARGRIDTOOLOPTIONSDLG 346
#define IDD_POLARGRIDTOOLOPTIONSDLG     347
#define IDR_XMLSTYLESHEETSVIEW          347
#define IDR_SVGCLIPPATHSDLG             348
#define IDD_EDITGRADIENTDLG             350
#define IDD_RGBSLIDERSDLG               351
#define IDD_CUSTOMSHAPETOOLOPTIONSDLG   352
#define IDC_BRUSH_WIDTH                 1110
#define IDC_BRUSH_HEIGHT                1112
#define IDC_BRUSH_ANGLE                 1113
#define IDC_BRUSH_SHOW                  1114
#define IDC_BRUSH_TIP                   1115
#define IDC_PREFSTRANSP_GRIDSIZE        1125
#define IDC_PREFSTRANSP_GRIDCOLORS      1126
#define IDC_PENADD                      10010
#define IDC_PENNEW                      10011
#define IDC_PENCLOSE                    10012
#define IDC_PENCONTINUE                 10013
#define IDC_PENCHANGELAST               10014
#define IDC_PENCONNECT                  10015
#define IDC_PENDELETE                   10016
#define IDC_SELECT_DUPLICATE            10017
#define IDC_SIZEBRUSH                   10018
#define ID_FILE_CUSTOMIZE               32774
#define ID_FILE_OPENSITE                32775
#define ID_VIEW_ZOOMIN                  32776
#define ID_VIEW_ZOOMOUT                 32777
#define ID_ASGRAPH_CHANGEMODEL_SEQUENCE 32778
#define ID_ASGRAPH_CHANGEMODEL_CHOICE   32779
#define ID_ASGRAPH_CHANGEMODEL_ALL      32780
#define ID_ASGRAPH_UNBOUNDED            32781
#define ID_ASGRAPH_OPTIONAL             32782
#define ID_FILE_NEWSITE                 32785
#define ID_VIEW_OPTIMALWIDTHS           32786
#define ID_XML_TABLE_DISPLAYASTABLE     32787
#define ID_XML_TABLE_ASCENDINGSORT      32788
#define ID_XML_TABLE_DESCENDINGSORT     32789
#define ID_OBJECT_GROUP                 32806
#define ID_OBJECT_UNGROUP               32807
#define ID_TYPE_PARAGRAPH               32867
#define ID_TYPE_CHARACTER               32868
#define ID_OBJECT_ARRANGE_BRINGTOFRONT  32894
#define ID_OBJECT_ARRANGE_BRINGFORWARD  32895
#define ID_OBJECT_ARRANGE_SENDBACKWARD  32896
#define ID_OBJECT_ARRANGE_SENDTOBACK    32897
#define ID_TOOL_SYMBOLSPRAYER           32901
#define ID_SVGTOOL_SELECT               32902
#define ID_SVGTOOL_DIRECT               32903
#define ID_SVGTOOL_ELLIPSE              32904
#define ID_SVGTOOL_CIRCLE               32905
#define ID_SVGTOOL_RECTANGLE            32906
#define ID_SVGTOOL_SCALE                32907
#define ID_SVGTOOL_ROTATE               32908
#define ID_TOOL_HAND                    32909
#define ID_SVGTOOL_PATHPEN              32910
#define ID_SVGTOOL_PATHADDANCHOR        32911
#define ID_SVGTOOL_PATHDELETEANCHOR     32912
#define ID_SVGTOOL_PATHCORNER           32913
#define ID_TOOL_ELLIPSEGRAPHIC          32914
#define ID_TOOL_RECTANGLEGRAPHIC        32915
#define ID_TOOL_TEXTPATH                32916
#define ID_TOOL_TEXT                    32917
#define ID_TOOL_ZOOM                    32918
#define ID_SVGTOOL_FREETRANSFORM        32920
#define ID_SVGTOOL_LINE                 32921
#define ID_TOOL_BULGE                   32922
#define ID_TOOL_TWIRL                   32923
#define ID_VIEW_CSSEDITOR               32925
#define ID_VIEW_WORDWRAP                32926
#define ID_VIEW_LINENUMBERS             32927
#define ID_FILE_MOUNTWORKGROUPSITE      32928
#define ID_WINDOW_NEWWINDOWONACTIVEELEMENT 32929
#define ID_XSL_ASSIGNXSL                32930
#define ID_XSL_GOTOXSL                  32931
#define ID_FILE_NEW_NEWSITEM            32934
#define ID_FILE_OPENURL                 32936
#define ID_FILTERS_NEWFILTER            32944
#define ID_WINDOW_FILTERLIBRARIES_OPEN  32945
#define ID_WINDOW_SYMBOLLIBRARIES_OPEN  32946
#define ID_EDIT_ADVANCED_MAKESELECTIONUPPERCASE 32947
#define ID_EDIT_ADVANCED_MAKESELECTIONLOWERCASE 32948
#define ID_EDIT_OPTIONS                 32949
#define ID_VIEW_VIEWWHITESPACE          32950
#define ID_EDIT_ADVANCED_TABIFYSELECTION 32951
#define ID_EDIT_ADVANCED_UNTABIFYSELECTION 32952
#define ID_SYMBOLS_PLACESYMBOL          32953
#define ID_WINDOW_SWATCHLIBRARIES_OPEN  32954
#define ID_DTDSCHEMA_ASSIGNDTD          32957
#define ID_DTDSCHEMA_DOCTYPEDTD_XHTML10STRICT 32958
#define ID_DTDSCHEMA_DOCTYPEDTD_XHTML10TRANSITIONAL 32959
#define ID_DTDSCHEMA_DOCTYPEDTD_XHTML10FRAMESET 32960
#define ID_SMILLAYOUTS_NEWTOPLAYOUT     32964
#define ID_TIMEGRAPH_OPTIONS            32965
#define ID_EDIT_XPATHQUERY              32967
#define ID_PARAGRAPH_ALIGNLEFT          32977
#define ID_PARAGRAPH_ALIGNRIGHT         32978
#define ID_PARAGRAPH_ALIGNCENTER        32979
#define ID_PARAGRAPH_ALIGNJUSTIFY       32980
#define ID_FORMATTING_FORMAT            32981
#define ID_FORMATTING_NUMBEREDLIST      32982
#define ID_FORMATTING_UNNUMBEREDLIST    32983
#define ID_INSERT_IMAGE                 32984
#define ID_INSERT_FORM_ONELINETEXTBOX   32985
#define ID_INSERT_FORM_CHECKBOX         32986
#define ID_INSERT_FORM_RADIOBUTTON      32987
#define ID_INSERT_FORM_PUSHBUTTON       32988
#define ID_INSERT_FORM_SCROLLINGTEXTBOX 32989
#define ID_INSERT_FORM_DROPDOWNMENU     32990
#define ID_TABLE_INSERT_TABLE           32993
#define ID_CSS_NEWIMPORTRULE            32994
#define ID_CSSPROPERTIES_TABBEDVIEW     32995
#define ID_FILTERLIBRARY_ADDTOFILTERS   32996
#define ID_FILTERS_SELECTALLUNUSED      32997
#define ID_SVGLIST_SMALLTHUMBNAILS      33000
#define ID_SVGLIST_LARGETHUMBNAILS      33001
#define ID_SVGLIST_SMALLLISTVIEW        33002
#define ID_SVGLIST_LARGELISTVIEW        33003
#define ID_ELEMENTMASK_MAKEMASK         33004
#define ID_SVGFILTERS_DELETEFILTER      33005
#define ID_SVGSWATCHES_DELETESWATCH     33006
#define ID_SVGTOOL_TOGGLEFILLSTROKE     33007
#define ID_FILE_PLACE                   33009
#define ID_EDITFILTER_GAUSSIANBLUR      33010
#define ID_EDITFILTER_BLEND             33011
#define ID_EDITFILTER_COMPOSITE         33012
#define ID_EDITFILTER_COLORMATRIX       33013
#define ID_EDITFILTER_CONVOLVEMATRIX    33014
#define ID_EDITFILTER_OFFSET            33015
#define ID_EDITFILTER_DISPLACEMENTMAP   33016
#define ID_OBJECT_PATH_ADDANCHORPOINTS  33021
#define ID_OBJECT_COMPOUNDPATH_MAKE     33022
#define ID_OBJECT_COMPOUNDPATH_RELEASE  33023
#define ID_SVGSWATCHES_NEWSOLIDCOLOR    33024
#define ID_SVGSWATCHES_NEWLINEARGRADIENT 33025
#define ID_SVGSWATCHES_NEWRADIALGRADIENT 33026
#define ID_OBJECT_CONVERTTOPATH         33027
#define ID_SVGTOOL_ROUNDEDRECTANGLE     33028
#define ID_OBJECT_TRANSFORM_CLEAR       33029
#define ID_OBJECT_TRANSFORM_CONSOLIDATE 33030
#define ID_EDITFILTER_DELETEPRIMITIVE   33031
#define ID_EDITFILTER_MERGE             33032
#define ID_NAVIGATOR_PALETTEOPTIONS     33033
#define ID_EDITFILTER_COMPONENTTRANSFER 33034
#define ID_CSS_NEWINTERNALSTYLEELEMENT  33035
#define ID_CSS_NEWCLASSSTYLE            33036
#define ID_VIEW_ACTUALSIZE              33037
#define ID_SVGOBJECTS_DELETESELECTION   33038
#define ID_SVGTOOL_PENCIL               33039
#define ID_SVGTOOL_POLYGON              33041
#define ID_SVGTOOL_POLYLINE             33042
#define ID_OBJECT_ALIGN_HORIZONTALLEFT  33043
#define ID_OBJECT_ALIGN_HORIZONTALRIGHT 33044
#define ID_OBJECT_ALIGN_HORIZONTALCENTER 33045
#define ID_OBJECT_ALIGN_VERTICALBOTTOM  33047
#define ID_OBJECT_ALIGN_VERTICALCENTER  33048
#define ID_OBJECT_ALIGN_VERTICALTOP     33049
#define ID_SVGTOOL_GRADIENT             33050
#define ID_SVGTOOL_RECTANGULARGRID      33052
#define ID_SVGTOOL_POLARGRID            33053
#define ID_SVGTOOL_WARP                 33054
#define ID_SVGTOOL_TWIRL                33055
#define ID_SVGTOOL_PUCKER               33056
#define ID_SVGTOOL_BLOAT                33057
#define ID_OBJECT_ENVELOPEDISTORT_MAKEWITHMESH 33059
#define ID_COLOR_INVERT                 33060
#define ID_COLOR_COMPLEMENT             33061
#define ID_SYMBOLS_NEWSYMBOL            33062
#define ID_SVGTOOL_SYMBOL_SPRAYER       33063
#define ID_SVGTOOL_SYMBOL_SHIFTER       33064
#define ID_SVGTOOL_SYMBOL_SCRUNCHER     33065
#define ID_SVGTOOL_SYMBOL_SIZER         33066
#define ID_SVGTOOL_SYMBOL_SPINNER       33067
#define ID_SVGTOOL_SYMBOL_SCREENER      33068
#define ID_SVGTOOL_SYMBOL_STYLER        33069
#define ID_OBJECT_EDITMASK              33071
#define ID_SELECT_BACK                  33072
#define ID_OBJECT_EDITFILTER            33073
#define ID_OBJECT_EDITCLIPPINGPATH      33074
#define ID_SVGFONTS_NEWFONT             33075
#define ID_SVGGLYPHS_NEWGLYPH           33076
#define ID_OBJECT_EDITPAINT             33077
#define ID_SVGOBJECTS_NEWLAYER          33078
#define ID_SVGOBJECTS_NEWSUBLAYER       33079
#define ID_SVGOBJECTS_SELECTIONOPTIONS  33080
#define ID_EDITFILTER_DIFFUSELIGHTING   33081
#define ID_EDITFILTER_SPECULARLIGHTING  33082
#define ID_EDITFILTER_FLOOD             33083
#define ID_EDITFILTER_TURBULENCE        33084
#define ID_EDITFILTER_MORPHOLOGY        33085
#define ID_EDITFILTER_IMAGE             33086
#define ID_EDITFILTER_TILE              33087
#define ID_SVGOBJECTS_NEWVIEWPORT       33088
#define ID_VIEW_SHOWMARKUP              33089
#define ID_FILE_RELOAD                  33090
#define ID_CSS_DISABLEDSTYLESHEET       33093
#define ID_TOOLS_MACRO_RECORD           33094
#define ID_DTDSCHEMA_DOCTYPEDTD_XHTML   33095
#define ID_DTDSCHEMA_DOCTYPEDTD_SVG     33096
#define ID_DTDSCHEMA_DOCTYPEDTD_SVG11   33097
#define ID_SCHEMA_CONTENTMODEL_OPTIONAL 33099
#define ID_SCHEMA_CONTENTMODEL_UNBOUNDED 33100
#define ID_SCHEMA_CONTENTMODEL_CHANGEMODEL_SEQUENCE 33101
#define ID_SCHEMA_CONTENTMODEL_CHANGEMODEL_CHOICE 33102
#define ID_SCHEMA_CONTENTMODEL_CHANGEMODEL_ALL 33103
#define ID_XML_INSERT_ATTRIBUTE         33104
#define ID_XML_INSERT_ELEMENT           33105
#define ID_XML_INSERT_TEXT              33106
#define ID_XML_INSERT_CDATA             33107
#define ID_XML_INSERT_COMMENT           33108
#define ID_XML_INSERT_DTDELEMENT        33109
#define ID_XML_INSERT_DTDATTLIST        33110
#define ID_XML_INSERT_DOCTYPE           33111
#define ID_INSERT_TIMELINE_SEQUENCE     33112
#define ID_INSERT_TIMELINE_PARALELL     33113
#define ID_INSERT_VIDEO                 33114
#define ID_INSERT_AUDIO                 33115
#define ID_FILE_NEW_DEFAULT             33117
#define ID_XML_INSERT_PROCESSINGINSTRUCTION 33119
#define ID_XML_ADDSTYLESHEET            33120
#define ID_SCHEMA_INSERT_ELEMENT        33121
#define ID_SCHEMA_INSERT_SEQUENCE       33122
#define ID_SCHEMA_INSERT_CHOICE         33123
#define ID_SCHEMA_INSERT_ALL            33124
#define ID_ANIMATION_ADDKEYFRAME        33125
#define ID_INSERT_FOREIGNOBJECT         33126
#define ID_SVGTOOL_FOREIGNOBJECT        33128
#define ID_ANIMATION_BEGIN              33129
#define ID_ANIMATION_END                33130
#define ID_SMIL_INSERT_IMAGE            33131
#define ID_SMIL_INSERT_VIDEO            33132
#define ID_SMIL_INSERT_AUDIO            33133
#define ID_TRANSITIONS_NEWTRANSITION    33135
#define ID_TRANSITIONS_DELETE           33136
#define ID_TRANSITIONS_SELECTALLUNUSED  33137
#define ID_TRANSITIONS_ANIMATE          33138
#define ID_COLOR_RGBSLIDERS             33139
#define ID_COLOR_HSLWHEEL               33140
#define ID_COLOR_NAMEDCOLORS            33141
#define ID_COLOR_GRAYSCALE              33142
#define ID_SCRIPTS_NEWSCRIPT            33143
#define ID_CSS_NEWCOLORPROFILE          33144
#define ID_CSS_NEWMEDIARULE             33145
#define ID_STYLESHEETS_INSERTXMLSTYLESHEET 33146
#define ID_SYMBOLS_DEFINESYMBOL         33147
#define ID_SYMBOLS_BREAKLINKTOSYMBOL    33148
#define ID_SVGSWATCHES_DEFINEPATTERN    33149
#define ID_SYMBOLS_SELECTALLUNUSED      33150
#define ID_EDIT_DESELECT                33151
#define ID_VIEW_RULERS                  33152
#define ID_VIEW_TRANSPARENCYGRID        33153
#define ID_SVGTOOL_EYEDROPPER           33154
#define ID_SVGTOOL_PAINTBUCKET          33155
#define ID_VIEW_GUIDES_MAKEGUIDES       33158
#define ID_VIEW_GUIDES_RELEASEGUIDES    33159
#define ID_SVGTOOL_CUSTOMSHAPE          33161
#define ID_TOOLPRESETS_NEW              33162
#define ID_SEGTYPE_CUBICBEZIER          33163
#define ID_SEGTYPE_QUADRATICBEZIER      33164
#define ID_SEGTYPE_LINE                 33165
#define ID_SEGTYPE_HORIZONTALLINE       33166
#define ID_SEGTYPE_VERTICALLINE         33167
#define ID_ANIMATION_ADDBEGINTIME       33169
#define ID_ANIMATION_ADDENDTIME         33170
#define ID_SVGCLIPPATHS_DEFINECLIPPATH  33171
#define ID_INSERT_SWITCH                33173
#define ID_TRANSITIONS_PLACETRANSITION  33174
#define ID_VIEW_TRANSFORMPAGE           33175
#define ID_CAMERA_PERSPECTIVE           33176
#define ID_CAMERA_LEFT                  33177
#define ID_CAMERA_RIGHT                 33178
#define ID_CAMERA_TOP                   33179
#define ID_CAMERA_BOTTOM                33180
#define ID_CAMERA_FRONT                 33181
#define ID_CAMERA_BACK                  33182
#define ID_DISPLAY_SMOOTH               33183
#define ID_DISPLAY_FLAT                 33184
#define ID_DISPLAY_WIREFRAME            33185
#define ID_DISPLAY_BOX                  33186
#define ID_FILE_NEW                     0xE100
#define ID_FILE_OPEN                    0xE101
#define ID_FILE_SAVE                    0xE103
#define ID_FILE_SAVE_AS                 0xE104
#define ID_FILE_PAGE_SETUP              0xE105
#define ID_FILE_PRINT                   0xE107
#define ID_EDIT_CLEAR                   0xE120
#define ID_EDIT_COPY                    0xE122
#define ID_EDIT_CUT                     0xE123
#define ID_EDIT_PASTE                   0xE125
#define ID_EDIT_PASTE_SPECIAL           0xE127
#define ID_EDIT_UNDO                    0xE12B
#define ID_EDIT_REDO                    0xE12C
#define ID_WINDOW_NEW                   0xE130
#define ID_WINDOW_SPLIT                 0xE135
#define ID_APP_ABOUT                    0xE140
#define ID_APP_EXIT                     0xE141
#define ID_VIEW_REFRESH                 0xE803

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        244
#define _APS_NEXT_COMMAND_VALUE         33187
#define _APS_NEXT_CONTROL_VALUE         234
#define _APS_NEXT_SYMED_VALUE           117
#endif
#endif
