#if !defined(AFX_STDAFX_H__CED51A28_ABDE_481F_B2D9_DECE3B0FD85D__INCLUDED_)
#define AFX_STDAFX_H__CED51A28_ABDE_481F_B2D9_DECE3B0FD85D__INCLUDED_

#define STRICT
#ifndef _WIN32_WINNT
#define _WIN32_WINNT 0x0400
#endif
//#define _ATL_APARTMENT_THREADED
//#define _ATL_FREE_THREADED

#define VOCEXT DECLSPEC_DLLEXPORT

#include "LFC/LFC.h"
#include "LMedia/LMedia.h"

#endif
