var namespace_system_1_1_debugger =
[
    [ "DebugFrame", "class_system_1_1_debugger_1_1_debug_frame.html", null ],
    [ "CallStackWnd", "class_system_1_1_debugger_1_1_call_stack_wnd.html", null ],
    [ "CRegistersWnd", "class_system_1_1_debugger_1_1_c_registers_wnd.html", null ],
    [ "striless", "class_system_1_1_debugger_1_1striless.html", null ],
    [ "SourceTextDocument", "class_system_1_1_debugger_1_1_source_text_document.html", null ],
    [ "DebuggerFrame", "class_system_1_1_debugger_1_1_debugger_frame.html", null ],
    [ "DebugBreakpoint", "class_system_1_1_debugger_1_1_debug_breakpoint.html", null ],
    [ "InstrPlaceholder", "struct_system_1_1_debugger_1_1_instr_placeholder.html", null ],
    [ "Breakpoint", "class_system_1_1_debugger_1_1_breakpoint.html", null ],
    [ "DebugThread", "class_system_1_1_debugger_1_1_debug_thread.html", null ],
    [ "DebugModule", "class_system_1_1_debugger_1_1_debug_module.html", null ],
    [ "DebugProcess", "class_system_1_1_debugger_1_1_debug_process.html", null ],
    [ "DebugRecv", "class_system_1_1_debugger_1_1_debug_recv.html", null ],
    [ "JavaDebugInfo", "class_system_1_1_debugger_1_1_java_debug_info.html", null ],
    [ "DebuggerCtx", "class_system_1_1_debugger_1_1_debugger_ctx.html", null ],
    [ "DisassemblyWnd", "class_system_1_1_debugger_1_1_disassembly_wnd.html", null ],
    [ "SourceEdit", "class_system_1_1_debugger_1_1_source_edit.html", null ],
    [ "SourceEditFrame", "class_system_1_1_debugger_1_1_source_edit_frame.html", null ],
    [ "ExpResult", "struct_system_1_1_debugger_1_1_exp_result.html", null ],
    [ "WatchItem", "class_system_1_1_debugger_1_1_watch_item.html", null ],
    [ "WatchExpression", "class_system_1_1_debugger_1_1_watch_expression.html", null ],
    [ "WatchWnd", "class_system_1_1_debugger_1_1_watch_wnd.html", null ],
    [ "filesmap", "namespace_system_1_1_debugger.html#a9f05768e1416aa949d2449386eef354b", null ],
    [ "tybreakpointmap", "namespace_system_1_1_debugger.html#afe78c3336063fb57cba52e8efada7776", null ],
    [ "tyhprocessmap", "namespace_system_1_1_debugger.html#abff9779c636cdb08046b0c4e460c06ca", null ],
    [ "tyhthreadmap", "namespace_system_1_1_debugger.html#a4d35c465f79a78ad9c83b2aef8717bd2", null ],
    [ "tylinebreakpointmap", "namespace_system_1_1_debugger.html#ab6ed0929870e019c41f245b951e47948", null ],
    [ "typrocessmap", "namespace_system_1_1_debugger.html#a20b5da6d9957951bb268175d80436067", null ]
];